import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Alert } from 'react-native';
import { shareAsync } from 'expo-sharing';
import * as FileSystem from 'expo-file-system';

interface Visit {
  id: string;
  siteName: string;
  date: string;
  status: 'pending' | 'completed' | 'in-progress';
  isCheckedIn: boolean;
  checkInTime?: string;
  checkOutTime?: string;
  latitude: number;
  longitude: number;
}

interface PDFReportButtonProps {
  visit: Visit;
}

export default function PDFReportButton({ visit }: PDFReportButtonProps) {
  const generatePDFReport = async () => {
    try {
      const reportContent = `
SOL YIELD SITE VISIT REPORT
===========================

Site: ${visit.siteName}
Date: ${visit.date}
Status: ${visit.status}
Location: ${visit.latitude}, ${visit.longitude}

Check-in Details:
${visit.checkInTime ? `Check-in Time: ${new Date(visit.checkInTime).toLocaleString()}` : 'Not checked in'}
${visit.checkOutTime ? `Check-out Time: ${new Date(visit.checkOutTime).toLocaleString()}` : 'Not checked out'}

Visit Summary:
- Site visited: ${visit.isCheckedIn ? 'Yes' : 'No'}
- Status: ${visit.status}
- Report generated: ${new Date().toLocaleString()}

Notes:
This is an automated report generated by the SolYield mobile application.
      `.trim();

      const fileName = `visit_report_${visit.id}_${Date.now()}.txt`;
      const fileUri = FileSystem.documentDirectory + fileName;
      
      await FileSystem.writeAsStringAsync(fileUri, reportContent, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      await shareAsync(fileUri, {
        mimeType: 'text/plain',
        dialogTitle: `Share Visit Report - ${visit.siteName}`,
      });

    } catch (error) {
      console.error('Error generating report:', error);
      Alert.alert('Error', 'Failed to generate report. Please try again.');
    }
  };

  return (
    <View style={styles.container}>
      <TouchableOpacity style={styles.button} onPress={generatePDFReport}>
        <Text style={styles.buttonText}>Generate & Share Report</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    margin: 16,
  },
  button: {
    backgroundColor: '#007AFF',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});
